# Generated by Django 3.0.4 on 2020-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='used_size',
            field=models.FloatField(default=0),
        ),
    ]
