# Generated by Django 3.0.4 on 2020-05-18 17:36

import cloud.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=2048)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_folders', to='cloud.CloudFolder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CloudData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('data', models.FileField(upload_to=cloud.models.user_directory_path)),
                ('description', models.TextField(blank=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.CloudFolder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clouds', to='users.UserProfile')),
            ],
        ),
    ]
