# Generated by Django 3.0.6 on 2021-03-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddata',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_datas', to='users.UserProfile'),
        ),
    ]
