# Generated by Django 3.0.4 on 2020-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddata',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
